<?php
function namsinh($nam)
{
$namsinh=array(
1924=>array('Giáp Tý','Hải Trung Kim (Vàng dưới biển)','Kim'),
1984=>array('Giáp Tý','Hải Trung Kim (Vàng dưới biển)','Kim'),
1925=>array('Ất Sửu','Hải Trung Kim (Vàng dưới biển)','Kim'),
1985=>array('Ất Sửu','Hải Trung Kim (Vàng dưới biển)','Kim'),
1926=>array('Bính Dần','Lư Trung Hỏa (Lửa bếp lò)','Hỏa'),
1986=>array('Bính Dần','Lư Trung Hỏa (Lửa bếp lò)','Hỏa'),
1927=>array('Đinh Mão','Lư Trung Hỏa (Lửa bếp lò)','Hỏa'),
1987=>array('Đinh Mão','Lư Trung Hỏa (Lửa bếp lò)','Hỏa'),
1928=>array('Mậu Thìn','Đại Lâm Mộc (Cây trong rừng lớn)','Mộc'),
1988=>array('Mậu Thìn','Đại Lâm Mộc (Cây trong rừng lớn)','Mộc'),
1929=>array('Kỷ Tỵ','Đại Lâm Mộc (Cây trong rừng lớn)','Mộc'),
1989=>array('Kỷ Tỵ','Đại Lâm Mộc (Cây trong rừng lớn)','Mộc'),
1930=>array('Canh Ngọ','Lộ Bàn Thổ (Đất bên đường)','Thổ'),
1990=>array('Canh Ngọ','Lộ Bàn Thổ (Đất bên đường)','Thổ'),
1931=>array('Tân Mùi','Lộ Bàn Thổ (Đất bên đường)','Thổ'),
1991=>array('Tân Mùi','Lộ Bàn Thổ (Đất bên đường)','Thổ'),
1932=>array('Nhâm Thân','Kiếm Phong Kim (Vàng ở mũi kiếm)','Kim'),
1992=>array('Nhâm Thân','Kiếm Phong Kim (Vàng ở mũi kiếm)','Kim'),
1933=>array('Quý Dậu','Kiếm Phong Kim (Vàng ở mũi kiếm)','Kim'),
1993=>array('Quý Dậu','Kiếm Phong Kim (Vàng ở mũi kiếm)','Kim'),
1934=>array('Giáp Tuất','Sơn Đầu Hỏa (Lửa đầu núi)','Hỏa'),
1994=>array('Giáp Tuất','Sơn Đầu Hỏa (Lửa đầu núi)','Hỏa'),
1935=>array('Ất Hợi','Sơn Đầu Hỏa (Lửa đầu núi)','Hỏa'),
1995=>array('Ất Hợi','Sơn Đầu Hỏa (Lửa đầu núi)','Hỏa'),
1936=>array('Bính Tý','Giang Hạ Thủy (Nước dưới khe)','Thủy'),
1996=>array('Bính Tý','Giang Hạ Thủy (Nước dưới khe)','Thủy'),
1937=>array('Đinh Sửu','Giang Hạ Thủy (Nước dưới khe)','Thủy'),
1997=>array('Đinh Sửu','Giang Hạ Thủy (Nước dưới khe)','Thủy'),
1938=>array('Mậu Dần','Thành Đầu Thổ (Đất trên mặt thành)','Thổ'),
1998=>array('Mậu Dần','Thành Đầu Thổ (Đất trên mặt thành)','Thổ'),
1939=>array('Kỷ Mão','Thành Đầu Thổ (Đất trên mặt thành)','Thổ'),
1999=>array('Kỷ Mão','Thành Đầu Thổ (Đất trên mặt thành)','Thổ'),
1940=>array('Canh Thìn','Bạch Lạp Kim (Vàng trong nến trắng)','Kim'),
2000=>array('Canh Thìn','Bạch Lạp Kim (Vàng trong nến trắng)','Kim'),
1941=>array('Tân Tỵ','Bạch Lạp Kim (Vàng trong nến trắng)','Kim'),
2001=>array('Tân Tỵ','Bạch Lạp Kim (Vàng trong nến trắng)','Kim'),
1942=>array('Nhâm Ngọ','Dương Liễu Mộc (Gỗ cây dương liễu)','Mộc'),
2002=>array('Nhâm Ngọ','Dương Liễu Mộc (Gỗ cây dương liễu)','Mộc'),
1943=>array('Quý Mùi','Dương Liễu Mộc (Gỗ cây dương liễu)','Mộc'),
2003=>array('Quý Mùi','Dương Liễu Mộc (Gỗ cây dương liễu)','Mộc'),
1944=>array('Giáp Thân','Tuyền Trung Thủy (Nước suối)','Thủy'),
2004=>array('Giáp Thân','Tuyền Trung Thủy (Nước suối)','Thủy'),
1945=>array('Ất Dậu','Tuyền Trung Thủy (Nước suối)','Thủy'),
2005=>array('Ất Dậu','Tuyền Trung Thủy (Nước suối)','Thủy'),
1946=>array('Bính Tuất','Ốc Thượng Thổ (Đất trên nóc nhà)','Thổ'),
2006=>array('Bính Tuất','Ốc Thượng Thổ (Đất trên nóc nhà)','Thổ'),
1947=>array('Đinh Hợi','Ốc Thượng Thổ (Đất trên nóc nhà)','Thổ'),
2007=>array('Đinh Hợi','Ốc Thượng Thổ (Đất trên nóc nhà)','Thổ'),
1948=>array('Mậu Tý','Thích Lịch Hỏa (Lửa sấm sét)','Hỏa'),
2008=>array('Mậu Tý','Thích Lịch Hỏa (Lửa sấm sét)','Hỏa'),
1949=>array('Kỷ Sửu','Thích Lịch Hỏa (Lửa sấm sét)','Hỏa'),
2009=>array('Kỷ Sửu','Thích Lịch Hỏa (Lửa sấm sét)','Hỏa'),
1950=>array('Canh Dân','Tòng Bá Mộc (Gỗ cây tùng bách)','Mộc'),
2010=>array('Canh Dân','Tòng Bá Mộc (Gỗ cây tùng bách)','Mộc'),
1951=>array('Tân Mão','Tòng Bá Mộc (Gỗ cây tùng bách)','Mộc'),
2011=>array('Tân Mão','Tòng Bá Mộc (Gỗ cây tùng bách)','Mộc'),
1952=>array('Nhâm Thìn','Trường Lưu Thủy (Nước sông dài)','Thủy'),
2012=>array('Nhâm Thìn','Trường Lưu Thủy (Nước sông dài)','Thủy'),
1953=>array('Quý Tỵ','Trường Lưu Thủy (Nước sông dài)','Thủy'),
2013=>array('Quý Tỵ','Trường Lưu Thủy (Nước sông dài)','Thủy'),
1954=>array('Giáp Ngọ','Sa Trung Kim (Vàng trong cát)','Kim'),
2014=>array('Giáp Ngọ','Sa Trung Kim (Vàng trong cát)','Kim'),
1955=>array('Ất Mùi','Sa Trung Kim (Vàng trong cát)','Kim'),
2015=>array('Ất Mùi','Sa Trung Kim (Vàng trong cát)','Kim'),
1956=>array('Bính Thân','Sơn Hạ Hỏa (Lửa chân núi)','Hỏa'),
2016=>array('Bính Thân','Sơn Hạ Hỏa (Lửa chân núi)','Hỏa'),
1957=>array('Đinh Dậu','Sơn Hạ Hỏa (Lửa chân núi)','Hỏa'),
2017=>array('Đinh Dậu','Sơn Hạ Hỏa (Lửa chân núi)','Hỏa'),
1958=>array('Mậu Tuất','Bình Địa Mộc (Cây ở đồng bằng)','Mộc'),
2018=>array('Mậu Tuất','Bình Địa Mộc (Cây ở đồng bằng)','Mộc'),
1959=>array('Kỷ Hợi','Bình Địa Mộc (Cây ở đồng bằng)','Mộc'),
2019=>array('Kỷ Hợi','Bình Địa Mộc (Cây ở đồng bằng)','Mộc'),
1960=>array('Canh Tý','Bích Thượng Thổ (Đất trên vách)','Thổ'),
2020=>array('Canh Tý','Bích Thượng Thổ (Đất trên vách)','Thổ'),
1961=>array('Tân Sửu','Bích Thượng Thổ (Đất trên vách)','Thổ'),
2021=>array('Tân Sửu','Bích Thượng Thổ (Đất trên vách)','Thổ'),
1962=>array('Nhâm Dần','Kim Bạch Kim (Vàng thép mỏng)','Kim'),
2022=>array('Nhâm Dần','Kim Bạch Kim (Vàng thép mỏng)','Kim'),
1963=>array('Quý Mão','Kim Bạch Kim (Vàng thép mỏng)','Kim'),
2023=>array('Quý Mão','Kim Bạch Kim (Vàng thép mỏng)','Kim'),
1964=>array('Giáp Thìn','Phúc Đăng Hỏa (Lửa trong đèn)','Hỏa'),
2024=>array('Giáp Thìn','Phúc Đăng Hỏa (Lửa trong đèn)','Hỏa'),
1965=>array('Ất Tỵ','Phúc Đăng Hỏa (Lửa trong đèn)','Hỏa'),
2025=>array('Ất Tỵ','Phúc Đăng Hỏa (Lửa trong đèn)','Hỏa'),
1966=>array('Bính Ngọ','Thiên Hà Thủy (Sông trên trời)','Thủy'),
2026=>array('Bính Ngọ','Thiên Hà Thủy (Sông trên trời)','Thủy'),
1967=>array('Đinh Mùi','Thiên Hà Thủy (Sông trên trời)','Thủy'),
2027=>array('Đinh Mùi','Thiên Hà Thủy (Sông trên trời)','Thủy'),
1968=>array('Mậu Thân','Đại Trạch Thổ (Đất diện tích lớn)','Thổ'),
2028=>array('Mậu Thân','Đại Trạch Thổ (Đất diện tích lớn)','Thổ'),
1969=>array('Kỷ Dậu','Đại Trạch Thổ (Đất diện tích lớn)','Thổ'),
2029=>array('Kỷ Dậu','Đại Trạch Thổ (Đất diện tích lớn)','Thổ'),
1970=>array('Canh Tuất','Thoa Xuyến Kim (Vàng làm đồ trang sức)','Kim'),
2030=>array('Canh Tuất','Thoa Xuyến Kim (Vàng làm đồ trang sức)','Kim'),
1971=>array('Tân Hợi','Thoa Xuyến Kim (Vàng làm đồ trang sức)','Kim'),
2031=>array('Tân Hợi','Thoa Xuyến Kim (Vàng làm đồ trang sức)','Kim'),
1972=>array('Nhâm Tý','Tang Đố Mộc (Gỗ cây dâu nuôi tằm)','Mộc'),
2032=>array('Nhâm Tý','Tang Đố Mộc (Gỗ cây dâu nuôi tằm)','Mộc'),
1973=>array('Quý Sửu','Tang Đố Mộc (Gỗ cây dâu nuôi tằm)','Mộc'),
2033=>array('Quý Sửu','Tang Đố Mộc (Gỗ cây dâu nuôi tằm)','Mộc'),
1974=>array('Giáp Dần','Đại Khê Thủy (Nước khe suối lớn)','Thủy'),
2034=>array('Giáp Dần','Đại Khê Thủy (Nước khe suối lớn)','Thủy'),
1975=>array('Ất Mão','Đại Khê Thủy (Nước khe suối lớn)','Thủy'),
2035=>array('Ất Mão','Đại Khê Thủy (Nước khe suối lớn)','Thủy'),
1976=>array('Bính Thìn','Sa Trung Thổ (Đất lẫn trong cát)','Thổ'),
2036=>array('Bính Thìn','Sa Trung Thổ (Đất lẫn trong cát)','Thổ'),
1977=>array('Đinh Tỵ','Sa Trung Thổ (Đất lẫn trong cát)','Thổ'),
2037=>array('Đinh Tỵ','Sa Trung Thổ (Đất lẫn trong cát)','Thổ'),
1978=>array('Mậu Ngọ','Thiên Thượng Hỏa (Lửa trên trời)','Hỏa'),
2038=>array('Mậu Ngọ','Thiên Thượng Hỏa (Lửa trên trời)','Hỏa'),
1979=>array('Kỷ Mùi','Thiên Thượng Hỏa (Lửa trên trời)','Hỏa'),
2039=>array('Kỷ Mùi','Thiên Thượng Hỏa (Lửa trên trời)','Hỏa'),
1980=>array('Canh Thân','Thạch Lựu Mộc (Gỗ cây thạch lựu)','Mộc'),
2040=>array('Canh Thân','Thạch Lựu Mộc (Gỗ cây thạch lựu)','Mộc'),
1981=>array('Tân Dậu','Thạch Lựu Mộc (Gỗ cây thạch lựu)','Mộc'),
2041=>array('Tân Dậu','Thạch Lựu Mộc (Gỗ cây thạch lựu)','Mộc'),
1982=>array('Nhâm Tuất','Đại Hải Thủy (Nước biển lớn)','Thủy'),
2042=>array('Nhâm Tuất','Đại Hải Thủy (Nước biển lớn)','Thủy'),
1983=>array('Quý Hợi','Đại Hải Thủy (Nước biển lớn)','Thủy'),
2043=>array('Quý Hợi','Đại Hải Thủy (Nước biển lớn)','Thủy'),
);
return $namsinh[$nam];
}
function nguhangso($so)
{
$nguhang=array(
1 => array('Giáp Tý ', 'Vàng trong biển', 'Kim'), 
2 => array('Ất Sửu ', 'Vàng trong biển', 'Kim'), 
3 => array('Bính Dần ', 'Lửa trong lò', 'Hoả'), 
4 => array('Ðinh Mão ', 'Lửa trong lò', 'Hoả'), 
5 => array('Mậu Thìn ', 'Gỗ trong rừng', 'Mộc'), 
6 => array('Kỷ Tị ', 'Gỗ trong rừng', 'Mộc'), 
7 => array('Canh Ngọ ', 'Ðất ven đường', 'Thổ'), 
8 => array('Tân Mùi ', 'Ðất ven đường', 'Thổ'), 
9 => array('Nhâm Thân ', 'Sắt đầu kiếm', 'Kim'), 
10 => array('Quí Dậu ', 'Sắt đầu kiếm', 'Kim'), 
11 => array('Giáp Tuất ', 'Lửa trên đỉnh núi', 'Hoả'), 
12 => array('Ất Hợi ', 'Lửa trên đỉnh núi', 'Hoả'), 
13 => array('Bính Tý ', 'Nước dưới lạch', 'Thuỷ'), 
14 => array('Ðinh Sửu ', 'Nước dưới lạch', 'Thuỷ'), 
15 => array('Mậu Dần ', 'Ðất đầu thành', 'Thổ'), 
16 => array('Kỷ Mão ', 'Ðất đầu thành', 'Thổ'), 
17 => array('Canh Thìn ', 'Kim bạch lạp', 'Kim'), 
18 => array('Tân Tị ', 'Kim bạch lạp', 'Kim'), 
19 => array('Nhâm Ngọ ', 'Gỗ dương liễu', 'Mộc'), 
20 => array('Quí Mùi ', 'Gỗ dương liễu', 'Mộc'), 
21 => array('Giáp Thân ', 'Nước trong khe', 'Thuỷ'), 
22 => array('Ất Dậu ', 'Nước trong khe', 'Thuỷ'), 
23 => array('Bính Tuất ', 'Ðất trên mái nhà', 'Thổ'), 
24 => array('Ðinh Hợi ', 'Ðất trên mái nhà', 'Thổ'), 
25 => array('Mậu Tý ', 'Lửa trong chớp', 'Hoả'), 
26 => array('Kỷ Sửu ', 'Lửa trong chớp', 'Hoả'), 
27 => array('Canh Dần ', 'Gỗ tùng Bách', 'Mộc'), 
28 => array('Tân Mão ', 'Gỗ tùng Bách', 'Mộc'), 
29 => array('Nhâm Thìn ', 'Nước giữa dòng', 'Thuỷ'), 
30 => array('Quí Tị ', 'Nước giữa dòng', 'Thuỷ'), 
31 => array('Giáp Ngọ ', 'Vàng trong cát', 'Kim'), 
32 => array('Ất Mùi ', 'Vàng trong cát', 'Kim'), 
33 => array('Bính Thân ', 'Lửa chân núi', 'Hoả'), 
34 => array('Ðinh Dậu ', 'Lửa chân núi', 'Hoả'), 
35 => array('Mậu Tuất ', 'Gỗ đồng bằng', 'Mộc'), 
36 => array('Kỷ Hợi ', 'Gỗ đồng bằng', 'Mộc'), 
37 => array('Canh Tý ', 'Ðất trên vách', 'Thổ'), 
38 => array('Tân Sửu ', 'Ðất trên vách', 'Thổ'), 
39 => array('Nhâm Dần ', 'Bạch kim', 'Kim'), 
40 => array('Quí Mão ', 'Bạch kim', 'Kim'), 
41 => array('Giáp Thìn ', 'Lửa đèn', 'Hoả'), 
42 => array('Ất Tị ', 'Lửa đèn', 'Hoả'), 
43 => array('Bính Ngọ ', 'Nước trên trời', 'thuỷ'), 
44 => array('Ðinh Mùi ', 'Nước trên trời', 'thuỷ'), 
45 => array('Mậu Thân ', 'Ðất vườn rộng', 'Thổ'), 
46 => array('Kỷ Dậu ', 'Ðất vườn rộng', 'Thổ'), 
47 => array('Canh Tuất ', 'Vàng trang sức', 'Kim'), 
48 => array('Tân Hợi ', 'Vàng trang sức', 'Kim'), 
49 => array('Nhâm Tý ', 'Gỗ dâu', 'Mộc'), 
50 => array('Quí Sửu ', 'Gỗ dâu', 'Mộc'), 
51 => array('Giáp Dần ', 'Nước giữa khe lớn', 'Thuỷ'), 
52 => array('Ất Mão ', 'Nước giữa khe lớn', 'Thuỷ'), 
53 => array('Bính Thìn ', 'Ðất trong cát', 'Thổ'), 
54 => array('Ðinh Tị ', 'Ðất trong cát', 'Thổ'), 
55 => array('Mậu Ngọ ', 'Lửa trên trời', 'Hoả'), 
56 => array('Kỷ Mùi ', 'Lửa trên trời', 'Hoả'), 
57 => array('Canh Thân ', 'Gỗ thạch Lựu', 'Mộc'), 
58 => array('Tân Dậu ', 'Gỗ thạch Lựu', 'Mộc'), 
59 => array('Nhâm Tuất ', 'Nước giữa biển', 'Thuỷ'), 
60 => array('Quí Hợi ', 'Nước giữa biển', 'Thuỷ')
);
$doi=str_replace("-","",$so%10-10);
echo $doi;
return $nguhang[$doi];
}
function amduong($dayso)
{
	$xdayso[1]=0;
	$xdayso[2]=0;
	for($i=1;$i<=strlen($dayso);$i++)
	{
		if (substr($dayso,0,$i)%2==0)
		$xdayso[2]++;
		else 
		$xdayso[1]++;
		
	}
	return $xdayso;
}
?>
